### ISSUE TITLE
anchor to local fragment is displayed incorrectly due to fixed top block

### ISSUE THREAD

**Issue by ruv** [GeraldWodni/forth-standard.org#13]
forth-standard.org web-site is affected by the bug described in "[HTML position:fixed page header and in-page anchors](https://stackoverflow.com/questions/4086107/html-positionfixed-page-header-and-in-page-anchors)" stackoverflow question, see the picture there.

To fix this issue you can adjust either `:target::before` pseudo-elements, or `html` and `body` elements on 50px (to scroll the body only, and the fixed block be outside the body). But since the fixed block's height can vary, the flawless pure CSS solution (without JavaScript) is to use flexible boxes (`display: flex;`) and scroll the main-content only, see an [example on jsfiddle](https://jsfiddle.net/501q4tyr/).

**Comment by GeraldWodni** [comment]
I played around with this for over an hour and only found partial solutions.

I think the real problem here is bootstrap, when I get around to it I would like to remove bootstrap totally and write a handcrafted solution. Bootstrap was chosen because I thought more people would want to directly interact with the code which is not the case. Personally I am not a big fan of bootstrap as is clutters up the html and hinders your own classes to some extend.

Having said that: If you or somebody else can come up with a workable solution which provides the following bullet points, it would be appreciated:
- No Javascript (Not that I have an issue with that, but a lot of visitors have disabled it)
- Cross Platform & Browser, at least: Chrome/Chromium & Firefox
- Responsive

I will add a label if somebody wants to do this, just a small note: This repo is not my working repo, so the code can be a bit outdated (I pushed the configuration into the working repo in error, so I cannot sync easily).

**Comment by GeraldWodni** [comment]
I just added the folloiwing snippet to `css/index.less`

```less
:target::before {
    height: @navbar-height;
}
```

this is quite ugly but gets the job done. If anybody comes up with a better solution, it is appreciated ;)

**Comment by ruv** [comment]
> This repo is not my working repo, so the code can be a bit outdated (I pushed the configuration into the working repo in error, so I cannot sync easily).

The configuration can be removed from the working repo by means of [git-filter-repo](https://github.com/newren/git-filter-repo).

I wanted to contribute to this repo, but there isn't much sense if the repo is outdated.

**Comment by GeraldWodni** [comment]
@ruv will look into that after EuroForth 2020. I also want the repos in GitHub to be synchronized. BTW are you attending EuroForth? It would really be cool to finally meet you albeit online only ;)

**Comment by ruv** [comment]
>  I also want the repos in GitHub to be synchronized. 

@GeraldWodni, how about synchronizing the repos? )
I would want to fix some bugs/issues.

**Comment by GeraldWodni** [comment]
@ruv Thanks for your patience, it took me quite a while to get this done.
I removed all user data with `bfg`. Should you encounter any remaints, please let me know, I really want to protect users' privacy as good as possible.

_PS: hope to see you at [EuroForth 2021](https://euro.theforth.net/)_

**Comment by ruv** [comment]
I have created a pull request #36, probably it can close this issue with scrolling to a local fragment.

**Comment by GeraldWodni** [comment]
PR merged, thank you @ruv for the CSS snippet!
