### ISSUE TITLE
Missing Forth-Version on https://forth-standard.org/systems

### ISSUE THREAD

**Issue by ekskirl** [GeraldWodni/forth-standard.org#31]
THere is a nice small Forth called PlanckForth I didn't see liested.
Look at https://github.com/nineties/planckforth
BG Ekkehard

**Comment by ruv** [comment]
Please, use the wiki web-page at https://github.com/ForthHub/wiki/wiki/Forth-Systems to list a Forth system.

**Comment by ekskirl** [comment]
Did it (2021-07-04) with starsupdate in last table.

Gesendet von Mail für Windows 10

Von: ruv
Gesendet: Donnerstag, 1. Juli 2021 18:00
An: GeraldWodni/forth-standard.org
Cc: Ekkehard Skirl; Author
Betreff: Re: [GeraldWodni/forth-standard.org] Missing Forth-Version on https://forth-standard.org/systems (#31)

Please, use the wiki web-page at https://github.com/ForthHub/wiki/wiki/Forth-Systems to list a Forth system.

**Comment by ruv** [comment]
Thank you! Then you might want to close this issue ([via web](https://github.com/GeraldWodni/forth-standard.org/issues/31#partial-new-comment-form-actions)).

**Comment by GeraldWodni** [comment]
`npm crawlSystems` used to be called by a cronjob when the website was still hosted on an oldschool server. Since I moved it into kubernetes, this function was never called again and I simply forgot about it.

Thanks for reminding me, it is now accessible via a hidden link which is called by a `CronJob` once a day and also re-reads systems.json afterwards (was missing in old version).
